Repository spcl/dace-vscode, pull requests merged in 2021-07, with the labels that each got.

#91 Bugfixes, and UI Improvements for editable select items
  media/components/sdfv/index.html
  media/components/sdfv/properties/properties.js
  media/components/sdfv/sdfv_overrides.css
  media/components/sdfv/util/vscode_renderer.js
  media/components/sdfv/vscode_sdfv.js
  media/lib/combobox/jquery-editable-select.min.css
  media/lib/combobox/jquery-editable-select.min.js
  src/daceInterface.ts
Labels: bug, enhancement, property-editor

#94 Handle messages after opening Viewer
  media/components/sdfgBreakpoints/index.html
  media/components/sdfv/index.html
  src/components/sdfgViewer.ts
Labels: bug, enhancement

#97 Transition to Monaco-Editor for Code properties
  media/components/sdfv/index.html
  media/components/sdfv/properties/properties.js
  media/components/sdfv/sdfv_overrides.css
  media/components/sdfv/vscode_sdfv.js
  package-lock.json
Labels: enhancement, feature request, property-editor

#104 Bugfixes
  media/components/outline/index.html
  media/components/outline/outline.js
  media/components/sdfv/index.html
  media/components/sdfv/messaging/message_handler.js
  media/components/sdfv/util/vscode_renderer.js
  media/components/transformation_list/transformation_list.js
  media/elements/treeview/treeview.js
  package.json
  src/extension.ts
Labels: bug
