Repository spcl/dace-vscode, pull requests merged in 2022-06, with the labels that each got.

#166 Add compressed extensions to SDFG
  package.json
Labels: enhancement, property-editor

#165 Fix overlays, library node expansion issues, and inability to edit complex or compound data types.
  backend/.gitignore
  backend/run_dace.py
  package-lock.json
  package.json
  src/dace_interface.ts
  src/utils/sdfg_meta_dict.json
  src/webclients/components/analysis/analysis.ts
  src/webclients/components/sdfv/analysis/analysis.ts
  src/webclients/components/sdfv/messaging/message_handler.ts
  src/webclients/components/sdfv/properties/properties.ts
  src/webclients/components/sdfv/utils/attributes_table.ts
  webpack.config.js
Labels: bug, enhancement, property-editor

#167 June Fixes Round 2
  .vscode/launch.json
  .vscodeignore
  backend/dace_vscode/transformations.py
  backend/run_dace.py
  media/components/sdfv/index.html
  package-lock.json
  package.json
  src/components/base_component.ts
  src/components/sdfg_viewer.ts
  src/dace_interface.ts
  src/extension.ts
  src/utils/utils.ts
  src/webclients/components/sdfv/vscode_sdfv.ts
  webpack.config.js
Labels: bug, enhancement, property-editor, python-integration
